services:
  db:
    image: postgres:16-alpine
    container_name: shop_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: shop_db
      POSTGRES_USER: shop_user
      POSTGRES_PASSWORD: hash_secure
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: shop_django_api
    command: >
      sh -c "sleep 5 &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DB_HOST: dbw
      DB_PORT: 5432
    depends_on:
      - db

volumes:
  postgres_data:



