services:
  db:
    image: postgres:16-alpine
    container_name: shop_postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shop_db
      - POSTGRES_USER=shop_user
      - POSTGRES_PASSWORD=hash_secure
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: shop_django_api
    # This command waits for the DB, runs migrations, then starts the server
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}  
      - DEBUG=${DEBUG}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: